package util

import model.Card
import model.CardRank
import model.Shape

object TestCards {
    val SPADE_ACE = Card.of(CardRank.ACE, Shape.SPADE)
    val DIAMOND_ACE = Card.of(CardRank.ACE, Shape.DIAMOND)
    val HEART_ACE = Card.of(CardRank.ACE, Shape.HEART)
    val CLUB_ACE = Card.of(CardRank.ACE, Shape.CLUB)
    val SPADE_KING = Card.of(CardRank.KING, Shape.SPADE)
    val DIAMOND_KING = Card.of(CardRank.KING, Shape.DIAMOND)
    val HEART_KING = Card.of(CardRank.KING, Shape.HEART)
    val CLUB_KING = Card.of(CardRank.KING, Shape.CLUB)
    val SPADE_QUEEN = Card.of(CardRank.QUEEN, Shape.SPADE)
    val DIAMOND_QUEEN = Card.of(CardRank.QUEEN, Shape.DIAMOND)
    val HEART_QUEEN = Card.of(CardRank.QUEEN, Shape.HEART)
    val CLUB_QUEEN = Card.of(CardRank.QUEEN, Shape.CLUB)
    val SPADE_JACK = Card.of(CardRank.JACK, Shape.SPADE)
    val DIAMOND_JACK = Card.of(CardRank.JACK, Shape.DIAMOND)
    val HEART_JACK = Card.of(CardRank.JACK, Shape.HEART)
    val CLUB_JACK = Card.of(CardRank.JACK, Shape.CLUB)
    val SPADE_TWO = Card.of(CardRank.TWO, Shape.SPADE)
    val DIAMOND_TWO = Card.of(CardRank.TWO, Shape.DIAMOND)
    val HEART_TWO = Card.of(CardRank.TWO, Shape.HEART)
    val CLUB_TWO = Card.of(CardRank.TWO, Shape.CLUB)
    val SPADE_THREE = Card.of(CardRank.THREE, Shape.SPADE)
    val DIAMOND_THREE = Card.of(CardRank.THREE, Shape.DIAMOND)
    val HEART_THREE = Card.of(CardRank.THREE, Shape.HEART)
    val CLUB_THREE = Card.of(CardRank.THREE, Shape.CLUB)
    val SPADE_FOUR = Card.of(CardRank.FOUR, Shape.SPADE)
    val DIAMOND_FOUR = Card.of(CardRank.FOUR, Shape.DIAMOND)
    val HEART_FOUR = Card.of(CardRank.FOUR, Shape.HEART)
    val CLUB_FOUR = Card.of(CardRank.FOUR, Shape.CLUB)
    val SPADE_FIVE = Card.of(CardRank.FIVE, Shape.SPADE)
    val DIAMOND_FIVE = Card.of(CardRank.FIVE, Shape.DIAMOND)
    val HEART_FIVE = Card.of(CardRank.FIVE, Shape.HEART)
    val CLUB_FIVE = Card.of(CardRank.FIVE, Shape.CLUB)
    val SPADE_SIX = Card.of(CardRank.SIX, Shape.SPADE)
    val DIAMOND_SIX = Card.of(CardRank.SIX, Shape.DIAMOND)
    val HEART_SIX = Card.of(CardRank.SIX, Shape.HEART)
    val CLUB_SIX = Card.of(CardRank.SIX, Shape.CLUB)
    val SPADE_SEVEN = Card.of(CardRank.SEVEN, Shape.SPADE)
    val DIAMOND_SEVEN = Card.of(CardRank.SEVEN, Shape.DIAMOND)
    val HEART_SEVEN = Card.of(CardRank.SEVEN, Shape.HEART)
    val CLUB_SEVEN = Card.of(CardRank.SEVEN, Shape.CLUB)
    val SPADE_EIGHT = Card.of(CardRank.EIGHT, Shape.SPADE)
    val DIAMOND_EIGHT = Card.of(CardRank.EIGHT, Shape.DIAMOND)
    val HEART_EIGHT = Card.of(CardRank.EIGHT, Shape.HEART)
    val CLUB_EIGHT = Card.of(CardRank.EIGHT, Shape.CLUB)
    val SPADE_NINE = Card.of(CardRank.NINE, Shape.SPADE)
    val DIAMOND_NINE = Card.of(CardRank.NINE, Shape.DIAMOND)
    val HEART_NINE = Card.of(CardRank.NINE, Shape.HEART)
    val CLUB_NINE = Card.of(CardRank.NINE, Shape.CLUB)
    val SPADE_TEN = Card.of(CardRank.TEN, Shape.SPADE)
    val DIAMOND_TEN = Card.of(CardRank.TEN, Shape.DIAMOND)
    val HEART_TEN = Card.of(CardRank.TEN, Shape.HEART)
    val CLUB_TEN = Card.of(CardRank.TEN, Shape.CLUB)
}
