package blackjack.model

val SPADE_ACE = Card(Denomination.ACE, Suit.SPADE)
val HEART_ACE = Card(Denomination.ACE, Suit.HEART)
val DIAMOND_ACE = Card(Denomination.ACE, Suit.DIAMOND)
val CLOVER_ACE = Card(Denomination.ACE, Suit.CLOVER)
val SPADE_TWO = Card(Denomination.TWO, Suit.SPADE)
val SPADE_FOUR = Card(Denomination.FOUR, Suit.SPADE)
val SPADE_FIVE = Card(Denomination.FIVE, Suit.SPADE)
val DIAMOND_SEVEN = Card(Denomination.SEVEN, Suit.DIAMOND)
val DIAMOND_NINE = Card(Denomination.NINE,Suit.DIAMOND)
val SPADE_NINE = Card(Denomination.NINE,Suit.SPADE)
val CLOVER_JACK = Card(Denomination.JACK,Suit.CLOVER)
val SPADE_KING = Card(Denomination.KING, Suit.SPADE)
val CLOVER_KING = Card(Denomination.KING, Suit.CLOVER)
val DIAMOND_KING = Card(Denomination.KING, Suit.DIAMOND)